## Numpy Tutorials 
- numpy is a general-purpose array-processing package. It provides a high-performance multidimentional array object and tools for wworking with these arrays . It is the fundamental package for scientific computing with python.

## What is an array?
- An array is a data structure that store values of same date type. In python , this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.

In [2]:
import numpy as np


In [3]:
my_list=[1,2,3,4,5,6]
arr=np.array(my_list)

In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr)

[1 2 3 4 5 6]


In [8]:
arr.shape

(6,)

In [12]:
## multidimentional array
my_list1=[1, 2, 3, 4, 5, 6]
my_list2=[5, 2, 7, 4, 9, 8]
my_list3=[10, 8, 0, 2, 4, 6]
print(my_list1,my_list2,my_list3)

[1, 2, 3, 4, 5, 6] [5, 2, 7, 4, 9, 8] [10, 8, 0, 2, 4, 6]


In [11]:
arr

array([1, 2, 3, 4, 5, 6])

In [21]:
arr1=np.array([my_list1,my_list2,my_list3])
print([arr1])

[array([[ 1,  2,  3,  4,  5,  6],
       [ 5,  2,  7,  4,  9,  8],
       [10,  8,  0,  2,  4,  6]])]


In [17]:
arr1.reshape(6,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  2,  7],
       [ 4,  9,  8],
       [10,  8,  0],
       [ 2,  4,  6]])

In [18]:
arr1.reshape(3,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 5,  2,  7,  4,  9,  8],
       [10,  8,  0,  2,  4,  6]])

In [20]:
arr1.shape


(3, 6)

# # Indexing 


In [22]:
## Accesing the array elements 

In [23]:
arr

array([1, 2, 3, 4, 5, 6])

In [26]:
arr[3]

4

In [8]:
import numpy as np
my_list1=[1, 2, 3, 4, 5, 6]
my_list2=[5, 2, 7, 4, 9, 8]
my_list3=[10, 8, 0, 2, 4, 6]
arr1=np.array([my_list1,my_list2,my_list3])
print([arr1])


[array([[ 1,  2,  3,  4,  5,  6],
       [ 5,  2,  7,  4,  9,  8],
       [10,  8,  0,  2,  4,  6]])]


In [11]:
arr1[0:3,1:3]

array([[2, 3],
       [2, 7],
       [8, 0]])

In [12]:
arr2=np.arange(0,10)

In [13]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr2=np.arange(0,10,step=2)
arr2

array([0, 2, 4, 6, 8])

In [17]:
arr2=np.linspace(1,10,50)
arr2

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [18]:
#copy() fuction and broadcasting 

In [22]:
arr=np.array([1,2,3,4,5,6])
arr[3:]=100
arr

array([  1,   2,   3, 100, 100, 100])

In [25]:
arr1=arr
arr1[3:]=500
arr1

array([  1,   2,   3, 500, 500, 500])

In [26]:
arr

array([  1,   2,   3, 500, 500, 500])

In [28]:
arr1=arr.copy()

In [29]:
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 500 500 500]
[   1    2    3 1000 1000 1000]


In [30]:
arr

array([  1,   2,   3, 500, 500, 500])

In [31]:
### some conditions very useful in exploratory data analysis

In [38]:
val=2
arr<2
#arr/2
#arr%2
#arr[arr<250]

array([ True, False, False, False, False, False])

In [39]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
arr1=np.arange(0,10).reshape(2,5)
arr2=np.arange(10,20).reshape(2,5)

In [41]:
arr1*arr2

array([[  0,  11,  24,  39,  56],
       [ 75,  96, 119, 144, 171]])

In [43]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [44]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
np.random.rand(3,3)

array([[0.47781373, 0.10839058, 0.26445814],
       [0.74397216, 0.63456368, 0.86742149],
       [0.49698012, 0.24428496, 0.61976178]])